#!/bin/bash

THIS=$(realpath "$0")
HERE=$(dirname "${THIS}") 

function upload {
  virsh vol-create-as --pool "${POOL}" --name "$2" --capacity 1m
  virsh vol-upload --pool "${POOL}" --vol "$2" --file "$1"
  virsh vol-list --pool "${POOL}"
}

function make_primary_disk {
  SOURCE="${IMAGES}/${IMAGE}"
  DISK="${IMAGES}/${PRIMARY}"
  truncate --reference "${SOURCE}" --size +${ROOT_SIZE} "${DISK}"
  virt-resize --quiet --expand "${ROOT_DEVICE}" "${IMAGES}/${IMAGE}" "${DISK}"
  upload "${DISK}" "${PRIMARY}"
  rm "${DISK}"
}

function make_cloud_init_disk {
  TEMP=$(mktemp --directory)
  CI_USER="${TEMP}/user-data"
  CI_META="${TEMP}/meta-data"
  CI_NETWORK="${TEMP}/network-config"
  envsubst < "${HERE}/cloud-init/user-data"             > "${CI_USER}"
  envsubst < "${HERE}/cloud-init/meta-data"             > "${CI_META}"
  envsubst < "${HERE}/cloud-init/network-config-static" > "${CI_NETWORK}"
}

function make_vm {
  virt-install \
    --import \
    --virt-type "kvm" \
    --boot "${BOOT}" \
    --osinfo "${OS}" \
    --name "${HOST}" \
    --memory "${MEMORY}" \
    --vcpus "${CPUS}" \
    --disk "vol=${POOL}/${PRIMARY},device=disk" \
    --cloud-init "user-data=${CI_USER},meta-data=${CI_META},network-config=${CI_NETWORK}" \
    --network "${NETWORK}" \
    --graphics "none" \
    --noautoconsole

  [ "${CONSOLE}" = "1" ] && virsh console "${HOST}"
}

function ruler {
  printf '%.s─' $(seq 1 $(tput cols))
}

# -------------------------------------------------------------------
# commands
#

function command_up {
	ruler
	echo "Building ${HOST}"
	echo

	make_primary_disk
	make_cloud_init_disk
	make_vm
}

function command_down {
  virsh destroy "${HOST}"
}

function command_ls {
  virsh list --all
}

function command_vols {
  virsh vol-list --pool "${POOL}"
}

function command_info {
  virsh dominfo --domain "$1"
  virsh domblklist --domain "$1"
}

function command_rm {
  virsh destroy "${HOST}"
  virsh undefine --nvram "${HOST}"
  virsh vol-delete --pool "${POOL}" --vol "${PRIMARY}"
}

function command_help {
  echo "fog - manage kvm VMs"
  echo
  echo "fog up            - build domain"
  echo "fog down          - stop domain"
  echo "fog ls            - list domains"
  echo "fog info <name>   - get domain info"
  echo "fog vols          - list volumes in pool \$POOL"
  echo "fog rm            - delete domain and volume"
}

IMAGES="${HERE}/images"
PRIMARY="${HOST}.qcow2"

export POOL="${POOL:-filesystems}"
export BOOT="${BOOT:-uefi}"
export PASSWORD="${PASSWORD:-letmein123}"

COMMAND="${1:-help}"
shift
command_${COMMAND} $@

# rm -rf "${TEMP}"
