#!/bin/bash

THIS=$(realpath "$0")
HERE=$(dirname "${THIS}") 

function upload {
  virsh vol-create-as --pool "${POOL}" --name "$2" --capacity 1m
  virsh vol-upload --pool "${POOL}" --vol "$2" --file "$1"
  virsh vol-list --pool "${POOL}"
}

function make_primary_disk {
  SOURCE="${IMAGES}/${IMAGE}"
  DISK="${IMAGES}/${PRIMARY}"
  truncate --reference "${SOURCE}" --size +${ROOT_SIZE} "${DISK}"
  virt-resize --quiet --expand "${ROOT_DEVICE}" "${SOURCE}" "${DISK}"
  upload "${DISK}" "${PRIMARY}"
  rm "${DISK}"
  DISK="vol=${POOL}/${PRIMARY},device=disk"
}

function template {
  local CONFIG=$(mktemp)
  envsubst < "${HERE}/cloud-init/$1" > "${CONFIG}"
  echo "${CONFIG}"
}

function make_cloud_init_disk {
  CI_USER=$(template "user-data")
  CI_META=$(template "meta-data")
  CI_NETWORK=$(template "network-config-${BOOTPROTO}")
  CLOUD_INIT="user-data=${CI_USER},meta-data=${CI_META},network-config=${CI_NETWORK}"
}

function make_vm {
  virt-install \
    --import \
    --virt-type "kvm" \
    --machine "${MACHINE}" \
    --boot "${BOOT}" \
    --osinfo "${OS}" \
    --name "${HOST}" \
    --memory "${MEMORY}" \
    --vcpus "${CPUS}" \
    --disk "${DISK}" \
    --cloud-init "${CLOUD_INIT}" \
    --network "${NETWORK}" \
    --graphics "none" \
    --noautoconsole

  [ "${CONSOLE}" = "1" ] && virsh console "${HOST}"
}

function ruler {
  printf '%.s─' $(seq 1 $(tput cols))
}

# -------------------------------------------------------------------
# commands
#

function command_up {
  ruler
  echo "Building ${HOST}"
  echo

  IMAGES="${HERE}/images"
  PRIMARY="${HOST}.qcow2"

  POOL="${POOL:-filesystems}"
  MACHINE="${MACHINE:-q35}"
  BOOT="${BOOT:-uefi}"
  PASSWORD="${PASSWORD:-letmein123}"
  BOOTPROTO="${BOOTPROTO:-static}"

  echo "Making root disk"
  make_primary_disk
  echo "Making Cloud-init disk"
  make_cloud_init_disk
  echo "Starting VM"
  make_vm
}

function command_down {
  virsh destroy "$1"
}

function command_ls {
  virsh list --all
}

function command_vols {
  POOL="${1:-filesystems}"
  virsh vol-list --pool "${POOL}"
}

function command_info {
  virsh dominfo --domain "$1"
  virsh domblklist --domain "$1"
}

function command_rm {
  POOL="filesystems"
  PRIMARY="$1.qcow2"
  virsh destroy "$1"
  virsh undefine --nvram "$1"
  virsh vol-delete --pool "${POOL}" --vol "${PRIMARY}"
}

function command_help {
  echo "fog - manage KVM VMs"
  echo
  echo "fog ls            - list domains"
  echo "fog up            - build domain"
  echo "fog down <name>   - stop domain"
  echo "fog info <name>   - get domain info"
  echo "fog rm <name>     - delete domain and volume"
  echo "fog vols <pool>   - list volumes in pool"
  echo
}

COMMAND="${1:-help}"
shift
command_${COMMAND} $@
