#!/bin/bash

POOL="filesystems"

function command_ls {
  virsh list --all
}

function command_vols {
  virsh vol-list --pool ${POOL}
}

function command_rm {
  virsh destroy $1
  virsh undefine $1
  virsh vol-delete --pool ${POOL} --vol "$1.qcow2"
  virsh list --all
  command_vols
}

COMMAND="$1"
shift
command_${COMMAND} $@
